### ISSUE TITLE
Remove show_slave_hosts from MySQLCollector metrics blacklist

### ISSUE THREAD

**Issue by rclagett** [Netuitive/omnibus-netuitive-agent#42]
mysql.Com_show_slave_hosts is the new metric to be collected which is excluded from collection by this regex entry: `|^Com_|`

**Comment by Grumblesmith** [comment]
Are we going to un-blacklist all the others, or just this one mysql.Com_show_slave_hosts metric?

**Comment by rclag1126** [comment]
The one, as the issue description states. Though, I’m open to un-blacklisting others if viewed as useful.

**Comment by rclagett** [comment]
OBE
